version: "3.8"

services:
  frontend:
    container_name: portfolio
    image: portfolio-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
